# Generated by Django 2.1 on 2018-08-11 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.CharField(choices=[(1, 'SPMAGIC'), (2, 'FALCON')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('isOnGifMonitor', models.BooleanField(default=False)),
                ('addedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Board.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ProntoTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastProntoDate', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
